### ISSUE TITLE
Request: Add stack traces tot he returned output when debug: true

### ISSUE THREAD

**Issue by sbrl** [protocol114/micro-http-router#2]
Hello,

I've discovered this package and it's working rather well for me, actually. The `debug: true` option on the router is cool, but not particularly useful unless it returns a stack trace too though.

Perhaps it could be enhanced?

**Comment by nickduncan7** [comment]
Thanks for the PR that does exactly that. It's been merged into master. I'll go ahead and close this issue since you took the initiative 👍

**Comment by nickduncan7** [comment]
Also, just wanted to let you know that I pushed your change into NPM, and also updated some dependencies. This included upgrading radix-router which changed how request parameters are accessed (a change for the better, in my opinion).

If you `npm update micro-http-router@latest` you should get the newest version including your changes :)

**Comment by sbrl** [comment]
Thanks! :D
