### ISSUE TITLE
Allow for Deleting Routes

### ISSUE THREAD

**Issue by nahtnam** [protocol114/micro-http-router#4]
Hello,

This package has an interesting property where you can re-define routes after the server starts. This is very handing for hot reloading in development mode. One problem is that if the method of the route changes from GET to POST or something similar, and you re-add the route, both routes will still be there. It would be cool if we could de-register a route at a certain path and method.

Thanks!

**Comment by nickduncan7** [comment]
Yeah, that does seem like fairly standard functionality in hindsight. D'oh! I'll add that as well. Thanks for the suggestion!

**Comment by nahtnam** [comment]
No problem. Another request is a `deleteAll` function. This is kind of specific to me but the reason I need it is:

I am working on a framework that uses micro under the hood. I added a pretty cool functionality where it will hot-swap routes when you're in the dev environment so you don't have to wait a second until your server restarts on change. However, when you change one route, I end up hot-reloading all of them (due to some other technical reasons), and so if I were to change the route from `/hello` to `/world`, both `/hello` and `/world` will point to that handler because there is no way to de-register the previous route. It would be cool to just wipe all routes, then add them back again. Of course, you don't have to implement this if it doesn't fall under the scope of the project.

Thanks!
